### ISSUE TITLE
Error when do catkin_make

### ISSUE THREAD

**Issue by canglangzhige** [IRVLab/direct_stereo_slam#1]
Hi, the job is great! But when I do "catkin_make" there are errors occur, how can I do with it?:

/home/sqw/catkin_ws/src/direct_stereo_slam/src/loop_closure/loop_detection/ScanContext.h:36:17: error: ‘flann’ has not been declared
                 flann::Matrix<float> &ringkey, SigType &signature,
                 ^~~~~
/home/sqw/catkin_ws/src/direct_stereo_slam/src/loop_closure/loop_detection/ScanContext.h:36:30: error: expected ‘,’ or ‘...’ before ‘<’ token
                 flann::Matrix<float> &ringkey, SigType &signature,
                              ^
/home/sqw/catkin_ws/src/direct_stereo_slam/src/loop_closure/loop_detection/ScanContext.cpp:79:28: error: ‘flann’ has not been declared
                            flann::Matrix<float> &ringkey, SigType &signature,
                            ^~~~~
/home/sqw/catkin_ws/src/direct_stereo_slam/src/loop_closure/loop_detection/ScanContext.cpp:79:41: error: expected ‘,’ or ‘...’ before ‘<’ token
                            flann::Matrix<float> &ringkey, SigType &signature,
                                         ^
/home/sqw/catkin_ws/src/direct_stereo_slam/src/loop_closure/loop_detection/ScanContext.cpp: In member function ‘void ScanContext::generate(const std::vector<Eigen::Matrix<double, 3, 1> >&, int)’:
/home/sqw/catkin_ws/src/direct_stereo_slam/src/loop_closure/loop_detection/ScanContext.cpp:84:48: error: ‘tfm_pca_rig’ was not declared in this scope
   align_points_PCA(pts_spherical, pts_aligned, tfm_pca_rig);
                                                ^~~~~~~~~~~
/home/sqw/catkin_ws/src/direct_stereo_slam/src/loop_closure/loop_detection/ScanContext.cpp:87:3: error: ‘ringkey’ was not declared in this scope
   ringkey = flann::Matrix<float>(new float[num_r_], 1, num_r_);

**Comment by jiawei-mo** [comment]
Hi,

Thank you for your attention to this project. Could you try installing FLANN library?
`sudo apt install libflann-dev`

Best,
Jiawei

**Comment by canglangzhige** [comment]
Thanks for your replay.
I have installed the libflann-dev, and it is the newest when I try it again in the terminal.
I try to add "#include <flann/util/matrix.h>" in the /catkin_ws/src/direct_stereo_slam/src/loop_closure/loop_detection/ScanContext.h, but it occurs to another error :

error: ‘flann_datatype_t’ does not name a type
         flann_datatype_t data_type;
         ^~~~~~~~~~~~~~~~
/usr/include/flann/util/serialization.h:19:9: error: ‘flann_algorithm_t’ does not name a type
         flann_algorithm_t index_type;
         ^~~~~~~~~~~~~~~~~
/usr/include/flann/util/serialization.h: In member function ‘void flann::serialization::SaveArchive::initBlock()’:
/usr/include/flann/util/serialization.h:401:19: error: ‘FLANNException’ was not declared in this scope
             throw FLANNException("Error allocating compression buffer");

**Comment by canglangzhige** [comment]
> Hi,
> 
> Thank you for your attention to this project. Could you try installing FLANN library? `sudo apt install libflann-dev`
> 
> Best, Jiawei

Thanks for your replay.
I have installed the libflann-dev, and it is the newest when I try it again in the terminal.
I try to add "#include <flann/util/matrix.h>" in the /catkin_ws/src/direct_stereo_slam/src/loop_closure/loop_detection/ScanContext.h, but it occurs to another error :

error: ‘flann_datatype_t’ does not name a type
         flann_datatype_t data_type;
         ^~~~~~~~~~~~~~~~
/usr/include/flann/util/serialization.h:19:9: error: ‘flann_algorithm_t’ does not name a type
         flann_algorithm_t index_type;
         ^~~~~~~~~~~~~~~~~
/usr/include/flann/util/serialization.h: In member function ‘void flann::serialization::SaveArchive::initBlock()’:
/usr/include/flann/util/serialization.h:401:19: error: ‘FLANNException’ was not declared in this scope
             throw FLANNException("Error allocating compression buffer");

**Comment by canglangzhige** [comment]
> Hi,
> 
> Thank you for your attention to this project. Could you try installing FLANN library? `sudo apt install libflann-dev`
> 
> Best, Jiawei

@jiawei-mo 

Thanks for your replay.
I have installed the libflann-dev, and it is the newest when I try it again in the terminal.
I try to add "#include <flann/util/matrix.h>" in the /catkin_ws/src/direct_stereo_slam/src/loop_closure/loop_detection/ScanContext.h, but it occurs to another error :

error: ‘flann_datatype_t’ does not name a type
         flann_datatype_t data_type;
         ^~~~~~~~~~~~~~~~
/usr/include/flann/util/serialization.h:19:9: error: ‘flann_algorithm_t’ does not name a type
         flann_algorithm_t index_type;
         ^~~~~~~~~~~~~~~~~
/usr/include/flann/util/serialization.h: In member function ‘void flann::serialization::SaveArchive::initBlock()’:
/usr/include/flann/util/serialization.h:401:19: error: ‘FLANNException’ was not declared in this scope
             throw FLANNException("Error allocating compression buffer");

**Comment by jiawei-mo** [comment]
Below is what I have done:

1. Fresh install Ubuntu 20.04 in VirtualBox
2. Install ROS noetic
3. Install the [dependencies](https://github.com/IRVLab/direct_stereo_slam/blob/master/dependencies.zip) and `sudo apt install libpcl-dev`
4. Compile this project using catkin_make

I did not find any error related to the flann library, I did not even install flann library by myself (might come with ROS). 

What operating system are you using?

**Comment by canglangzhige** [comment]
> 

@jiawei-mo 
I run it the same way as you, except that I use Ubuntu 20.04 in dual system mode. 
Maybe it's other reasons. I will try to deal with this problem.
Thank you!

**Comment by canglangzhige** [comment]
> > 
> 
> @jiawei-mo I run it the same way as you, except that I use Ubuntu 20.04 in dual system mode. Maybe it's other reasons. I will try to deal with this problem. Thank you!

What version of opencv are you using? 
When I add  #include <flann/util/matrix.h>   in  / home/sqw/catkin_ws/src/direct_stereo_slam/src/loop_closure/loop_detection/ScanContext.h, the error disappeared.  
It seems like flann::Matrix doesn't definition. 
But new problem appeared:
/usr/include/flann/util/serialization.h:18:9: error: 'flann_datatype_t' does not name a type
          flann_datatype_t data_type; 
Some people say that this is because pcl and opencv use flann at the same time and there is a conflict.
I use Ubuntu 20.04, opencv 4.2 and pcl 1.0.

**Comment by jiawei-mo** [comment]
My system info: Ubuntu 20.04, libopencv 4.2 and libpcl 1.10. 
My OpenCV library comes with ROS, not sure if that make difference. I also find libflann1.9 in my library, which I believe also comes with ROS. As I mentioned previously, I only installed ROS and libpcl in my freshly installed Ubuntu.
