### ISSUE TITLE
How to use dslam.txt to compare with the groundtruth?

### ISSUE THREAD

**Issue by xmcchv** [IRVLab/direct_stereo_slam#2]
Hi,fortunately,i get the result on kitti dataset seq_00,but it's format differ from the kitti groundtruth ,how can i use it
[dslam.txt](https://github.com/IRVLab/direct_stereo_slam/files/8563727/dslam.txt)

**Comment by jiawei-mo** [comment]
Hi,

The output is formatted as [incoming_id, x, y, z]. You can modify the output in these [lines](https://github.com/IRVLab/direct_stereo_slam/blob/master/src/loop_closure/LoopHandler.cpp#L74-L76).

Best,
Jiawei

**Comment by xmcchv** [comment]
thanks a lot : )

**Comment by empty-spacebar** [comment]
> 
Hi,
We run DSV with KITTI  seq_00 too, but it performs slowly, did it happen on your computer?
