### ISSUE TITLE
REQUIRED process [direct_stereo_slam-2] has died!

### ISSUE THREAD

**Issue by garriton** [IRVLab/direct_stereo_slam#3]
i use
ubuntu 20.04 in docker
ros-noetic-desktop-full
dependencies provided by README.md, dependencies.zip

when i run the kitti_2011_09_26_drive_0002_synced.bag, occur this error:
**Reading Calibration from file /home/direct_stereo_slam/cams/kitti/0_2/camera1.txt ... found!
Input resolution: 1241 376
In: 718.856000 718.856000 607.192800 185.215700 0.000000
Out: Failed to Read Output pars... not rectifying.**

the whole terminal msg is:

```
... logging to /root/.ros/log/c1a1e294-d2c8-11ec-b31a-0242ac110002/roslaunch-9a80a7bcab52-5771.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://9a80a7bcab52:42635/

SUMMARY
========

PARAMETERS

 * /direct_stereo_slam/T_stereo/cols: 4
 * /direct_stereo_slam/T_stereo/data: [1, 0, 0, -0.5372...
 * /direct_stereo_slam/T_stereo/rows: 4
 * /direct_stereo_slam/bag: /home/direct_ster...
 * /direct_stereo_slam/calib0: /home/direct_ster...
 * /direct_stereo_slam/calib1: /home/direct_ster...
 * /direct_stereo_slam/topic0: /left/image_raw
 * /direct_stereo_slam/topic1: /right/image_raw
 * /rosdistro: noetic
 * /rosversion: 1.15.14

NODES
  /
    direct_stereo_slam (direct_stereo_slam/slam_node)

auto-starting new master
process[master]: started with pid [5779]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to c1a1e294-d2c8-11ec-b31a-0242ac110002
process[rosout-1]: started with pid [5789]
started core service [/rosout]
process[direct_stereo_slam-2]: started with pid [5796]

=============== PRESET Settings: ===============
DEFAULT settings:

- 2000 active points

- 5-7 active frames

- 1-6 LM iteration each KF

- original image resolution

  PHOTOMETRIC MODE WITHOUT CALIBRATION!
  ==============================================

  Reading Calibration from file /home/direct_stereo_slam/cams/kitti/0_2/camera0.txt ... found!
  Input resolution: 1241 376
  In: 718.856000 718.856000 607.192800 185.215700 0.000000
  Out: Failed to Read Output pars... not rectifying.
  Reading Calibration from file /home/direct_stereo_slam/cams/kitti/0_2/camera1.txt ... found!
  Input resolution: 1241 376
  In: 718.856000 718.856000 607.192800 185.215700 0.000000
  Out: Failed to Read Output pars... not rectifying.
  ================================================================================REQUIRED process [direct_stereo_slam-2] has died!
  process has died [pid 5796, exit code -11, cmd /root/catkin_ws/devel/lib/direct_stereo_slam/slam_node __name:=direct_stereo_slam __log:=/root/.ros/log/c1a1e294-d2c8-11ec-b31a-0242ac110002/direct_stereo_slam-2.log].
  log file: /root/.ros/log/c1a1e294-d2c8-11ec-b31a-0242ac110002/direct_stereo_slam-2*.log

  Initiating shutdown!
  ================================================================================

  [direct_stereo_slam-2] killing on exit
  [rosout-1] killing on exit
  [master] killing on exit
  shutting down processing monitor...
  ... shutting down processing monitor complete
  done
```

![image](https://user-images.githubusercontent.com/52850638/168305292-5127ea95-ed37-40b8-ac85-f1872d069481.png)

my kitti.launch:

```
<launch>
  <arg name="bag" default=""/>
  <arg name="seq" default="4_12"/>

  <rosparam command="load" file="/home/direct_stereo_slam/cams/kitti/0_2/T_stereo.yaml" ns="direct_stereo_slam"/>
  <node name="direct_stereo_slam" pkg="direct_stereo_slam" type="slam_node" output="screen" required="true">
    <param name="topic0" value="/left/image_raw" />
    <param name="topic1" value="/right/image_raw" />
    <param name="calib0" value="/home/direct_stereo_slam/cams/kitti/0_2/camera0.txt" />
    <param name="calib1" value="/home/direct_stereo_slam/cams/kitti/0_2/camera1.txt" />
    <param name="bag" value="/home/direct_stereo_slam/kitti/kitti_2011_09_26_drive_0002_synced.bag" />
    <!-- <param name="scale_opt_thres" value="-1" /> -->
  </node>

  </launch>
```

all the path exists.

log file:

```
[roslaunch][INFO] 2022-05-13 14:04:02,516: process[direct_stereo_slam-1]: args[['/root/catkin_ws/devel/lib/direct_stereo_slam/slam_node', '__name:=direct_stereo_slam']]
[roslaunch][INFO] 2022-05-13 14:04:02,516: ... created process [direct_stereo_slam-1]
[roslaunch.pmon][INFO] 2022-05-13 14:04:02,516: ProcessMonitor.register[direct_stereo_slam-1]
[roslaunch.pmon][INFO] 2022-05-13 14:04:02,516: ProcessMonitor.register[direct_stereo_slam-1] complete
[roslaunch][INFO] 2022-05-13 14:04:02,516: ... registered process [direct_stereo_slam-1]
[roslaunch][INFO] 2022-05-13 14:04:02,516: process[direct_stereo_slam-1]: starting os process
[roslaunch][INFO] 2022-05-13 14:04:02,516: process[direct_stereo_slam-1]: start w/ args [['/root/catkin_ws/devel/lib/direct_stereo_slam/slam_node', '__name:=direct_stereo_slam', '__log:=/root/.ros/log/85e8245a-d2c5-11ec-acbf-0242ac110002/direct_stereo_slam-1.log']]
[roslaunch][INFO] 2022-05-13 14:04:02,516: process[direct_stereo_slam-1]: cwd will be [/root/.ros]
[roslaunch][INFO] 2022-05-13 14:04:02,519: process[direct_stereo_slam-1]: started with pid [5239]
[roslaunch][INFO] 2022-05-13 14:04:02,519: ... successfully launched [direct_stereo_slam-1]
[roslaunch][INFO] 2022-05-13 14:04:02,519: ... launch_nodes complete
[roslaunch.pmon][INFO] 2022-05-13 14:04:02,519: registrations completed <ProcessMonitor(ProcessMonitor-1, started daemon 140120816346880)>
[roslaunch.parent][INFO] 2022-05-13 14:04:02,519: ... roslaunch parent running, waiting for process exit
[roslaunch][INFO] 2022-05-13 14:04:02,519: spin
[roslaunch][ERROR] 2022-05-13 14:04:02,858: ================================================================================REQUIRED process [direct_stereo_slam-1] has died!
process has died [pid 5239, exit code -11, cmd /root/catkin_ws/devel/lib/direct_stereo_slam/slam_node __name:=direct_stereo_slam __log:=/root/.ros/log/85e8245a-d2c5-11ec-acbf-0242ac110002/direct_stereo_slam-1.log].
log file: /root/.ros/log/85e8245a-d2c5-11ec-acbf-0242ac110002/direct_stereo_slam-1*.log

Initiating shutdown!
================================================================================

[roslaunch.pmon][INFO] 2022-05-13 14:04:02,958: ProcessMonitor._post_run <ProcessMonitor(ProcessMonitor-1, started daemon 140120816346880)>
[roslaunch.pmon][INFO] 2022-05-13 14:04:02,959: ProcessMonitor._post_run <ProcessMonitor(ProcessMonitor-1, started daemon 140120816346880)>: remaining procs are [<roslaunch.nodeprocess.LocalProcess object at 0x7f706b83dc10>]
[roslaunch.pmon][INFO] 2022-05-13 14:04:02,959: ProcessMonitor exit: killing direct_stereo_slam-1
[roslaunch][INFO] 2022-05-13 14:04:02,959: [direct_stereo_slam-1] killing on exit
[roslaunch.pmon][INFO] 2022-05-13 14:04:02,961: ProcessMonitor exit: cleaning up data structures and signals
[roslaunch.pmon][INFO] 2022-05-13 14:04:02,961: ProcessMonitor exit: pmon has shutdown
[roslaunch][INFO] 2022-05-13 14:04:03,021: process monitor is done spinning, initiating full shutdown
[roslaunch][INFO] 2022-05-13 14:04:03,021: runner.stop()
[roslaunch][INFO] 2022-05-13 14:04:03,021: shutting down processing monitor...
[roslaunch][INFO] 2022-05-13 14:04:03,021: shutting down processing monitor <ProcessMonitor(ProcessMonitor-1, stopped daemon 140120816346880)>
[roslaunch.pmon][INFO] 2022-05-13 14:04:03,021: ProcessMonitor.shutdown <ProcessMonitor(ProcessMonitor-1, stopped daemon 140120816346880)>
[roslaunch][INFO] 2022-05-13 14:04:03,021: ... shutting down processing monitor complete
[roslaunch][INFO] 2022-05-13 14:04:03,021: done
[roslaunch.pmon][INFO] 2022-05-13 14:04:03,021: ProcessMonitor.shutdown <ProcessMonitor(ProcessMonitor-1, stopped daemon 140120816346880)>
[rospy.core][INFO] 2022-05-13 14:04:03,021: signal_shutdown [atexit]
```

can u help?

**Comment by jiawei-mo** [comment]
It looks like that the calibration file is not read correctly. Check [this](https://github.com/JakobEngel/dso/blob/master/src/util/Undistort.cpp#L811-L837) for details.
Are you using the provided camera0 and camera1 files? if not, please show me your camera files.

**Comment by garriton** [comment]
> It looks like that the calibration file is not read correctly. Check [this](https://github.com/JakobEngel/dso/blob/master/src/util/Undistort.cpp#L811-L837) for details. Are you using the provided camera0 and camera1 files? if not, please show me your camera files.

I use the "\direct_stereo_slam\cams\kitti\0_2\camera0.txt" and "\direct_stereo_slam\cams\kitti\0_2\camera1.txt" git from this repositories
And didn't change them.

camera0.txt：
```
Pinhole 718.8560 718.8560 607.1928 185.2157 0
1241 376
crop
1232 368
```

camera1.txt：
```
Pinhole 718.8560 718.8560 607.1928 185.2157 0
1241 376
crop
1232 368
```

The data i used is raw data of KITTI, which is "kitti_2011_09_26_drive_0002_synced" in http://www.cvlibs.net/datasets/kitti/raw_data.php
![image](https://user-images.githubusercontent.com/52850638/168457883-3f8c3a88-5b65-4c18-a231-2796a287f4db.png)

**Comment by garriton** [comment]
I use the dos2unix to the calibration file,and it fixed.

But occurs the new error
```
Reading Calibration from file /home/direct_stereo_slam/cams/kitti/0_2/camera0.txt ... found!
Input resolution: 1241 376
In: 718.856000 718.856000 607.192800 185.215700 0.000000
Out: Rectify Crop
Output resolution: 1232 368
finding CROP optimal new model!
initial range: x: -0.8530 - 0.8890; y: -0.2602 - 0.2666!
iteration 00001: range: x: -0.8488 - 0.8846; y: -0.2602 - 0.2666!
iteration 00002: range: x: -0.8445 - 0.8801; y: -0.2602 - 0.2666!
iteration 00003: range: x: -0.8445 - 0.8801; y: -0.2589 - 0.2653!
iteration 00004: range: x: -0.8445 - 0.8801; y: -0.2576 - 0.2640!
iteration 00005: range: x: -0.8445 - 0.8801; y: -0.2576 - 0.2640!

Rectified Kamera Matrix:
713.759       0 602.796
      0 703.657 181.248
      0       0       1

NO PHOTOMETRIC Calibration!
Reading Photometric Calibration from file
PhotometricUndistorter: Could not open file!
Reading Calibration from file /home/direct_stereo_slam/cams/kitti/0_2/camera1.txt ... found!
Input resolution: 1241 376
In: 718.856000 718.856000 607.192800 185.215700 0.000000
Out: Rectify Crop
Output resolution: 1232 368
finding CROP optimal new model!
initial range: x: -0.8530 - 0.8890; y: -0.2602 - 0.2666!
iteration 00001: range: x: -0.8488 - 0.8846; y: -0.2602 - 0.2666!
iteration 00002: range: x: -0.8445 - 0.8801; y: -0.2602 - 0.2666!
iteration 00003: range: x: -0.8445 - 0.8801; y: -0.2589 - 0.2653!
iteration 00004: range: x: -0.8445 - 0.8801; y: -0.2576 - 0.2640!
iteration 00005: range: x: -0.8445 - 0.8801; y: -0.2576 - 0.2640!

Rectified Kamera Matrix:
713.759       0 602.796
      0 703.657 181.248
      0       0       1

NO PHOTOMETRIC Calibration!
Reading Photometric Calibration from file
PhotometricUndistorter: Could not open file!
using pyramid levels 0 to 4. coarsest resolution: 77 x 23!
Start Loop Thread
error: XDG_RUNTIME_DIR not set in the environment.
Framebuffer with requested attributes not available. Using available framebuffer. You may see visual artifacts.

************** Statistics (ms) ***************
===========VO Time============
feature_detect -nan x 0
scale_opt -nan x 0
dso_opt -nan x 0
======Loop Closure Time=======
pts_generation -nan x 0
sc_generation -nan x 0
search_ringkey -nan x 0
search_sc -nan x 0
direct_est -nan x 0
icp -nan x 0
pose_graph_opt -nan x 0
loop_count: 0 (direct) + 0 (icp)
==============================
per_frame -nan x 0
**********************************************


Finished Loop Thread
================================================================================REQUIRED process [direct_stereo_slam-2] has died!
process has died [pid 787, exit code 1, cmd /root/catkin_ws/devel/lib/direct_stereo_slam/slam_node __name:=direct_stereo_slam __log:=/root/.ros/log/d8b40378-d411-11ec-b103-0242ac110002/direct_stereo_slam-2.log].
log file: /root/.ros/log/d8b40378-d411-11ec-b103-0242ac110002/direct_stereo_slam-2*.log
Initiating shutdown!
================================================================================
[direct_stereo_slam-2] killing on exit
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
```

Thank u for your reply, I will try to fix it.

**Comment by YznMur** [comment]
@garriton @jiawei-mo Hi
I have the same problem. Have you managed to fix this bug?

**Comment by garriton** [comment]
> @garriton @jiawei-mo Hi I have the same problem. Have you managed to fix this bug?

I use the dos2unix to the calibration file, and it fixed.

**Comment by YznMur** [comment]
I mean the new error :  "error: XDG_RUNTIME_DIR not set in the environment." and the "nan" values

**Comment by garriton** [comment]
> I mean the new error : "error: XDG_RUNTIME_DIR not set in the environment." and the "nan" values

for error: XDG_RUNTIME_DIR
change the launch file.
add parameter:```<param name="nogui" value="true" />```

for the "nan" values
change the topic0 and topic1 to your rosbag topic

then i run the direct_stereo_slam, in 3000 + its ,occur the "REQUIRED process [direct_stereo_slam-2] has died!
process has died" again , but still haven't solved it, if you occurs it too, pls help

**Comment by YznMur** [comment]
``` PARAMETERS
 * /direct_stereo_slam/T_stereo/cols: 4
 * /direct_stereo_slam/T_stereo/data: [1, 0, 0, -0.5372...
 * /direct_stereo_slam/T_stereo/rows: 4
 * /direct_stereo_slam/bag: /home/user/catkin...
 * /direct_stereo_slam/calib0: /home/user/catkin...
 * /direct_stereo_slam/calib1: /home/user/catkin...
 * /direct_stereo_slam/nogui: True
 * /direct_stereo_slam/topic0: /kitti/camera_col...
 * /direct_stereo_slam/topic1: /kitti/camera_col...
 * /rosdistro: noetic
 * /rosversion: 1.15.14

NODES
  /
    direct_stereo_slam (direct_stereo_slam/slam_node)

ROS_MASTER_URI=http://localhost:11311

process[direct_stereo_slam-1]: started with pid [491]

=============== PRESET Settings: ===============
DEFAULT settings:
- 2000 active points
- 5-7 active frames
- 1-6 LM iteration each KF
- original image resolution
PHOTOMETRIC MODE WITHOUT CALIBRATION!
==============================================
Reading Calibration from file /home/user/catkin_ws/src/direct_stereo_slam/cams/kitti/0_2/camera0.txt ... found!
Input resolution: 1241 376
In: 718.856000 718.856000 607.192800 185.215700 0.000000
Out: Rectify Crop
Output resolution: 1232 368
finding CROP optimal new model!
initial range: x: -0.8530 - 0.8890; y: -0.2602 - 0.2666!
iteration 00001: range: x: -0.8488 - 0.8846; y: -0.2602 - 0.2666!
iteration 00002: range: x: -0.8445 - 0.8801; y: -0.2602 - 0.2666!
iteration 00003: range: x: -0.8445 - 0.8801; y: -0.2589 - 0.2653!
iteration 00004: range: x: -0.8445 - 0.8801; y: -0.2576 - 0.2640!
iteration 00005: range: x: -0.8445 - 0.8801; y: -0.2576 - 0.2640!

Rectified Kamera Matrix:
713.759       0 602.796
      0 703.657 181.248
      0       0       1

NO PHOTOMETRIC Calibration!
Reading Photometric Calibration from file 
PhotometricUndistorter: Could not open file!
Reading Calibration from file /home/user/catkin_ws/src/direct_stereo_slam/cams/kitti/0_2/camera1.txt ... found!
Input resolution: 1241 376
In: 718.856000 718.856000 607.192800 185.215700 0.000000
Out: Rectify Crop
Output resolution: 1232 368
finding CROP optimal new model!
initial range: x: -0.8530 - 0.8890; y: -0.2602 - 0.2666!
iteration 00001: range: x: -0.8488 - 0.8846; y: -0.2602 - 0.2666!
iteration 00002: range: x: -0.8445 - 0.8801; y: -0.2602 - 0.2666!
iteration 00003: range: x: -0.8445 - 0.8801; y: -0.2589 - 0.2653!
iteration 00004: range: x: -0.8445 - 0.8801; y: -0.2576 - 0.2640!
iteration 00005: range: x: -0.8445 - 0.8801; y: -0.2576 - 0.2640!

Rectified Kamera Matrix:
713.759       0 602.796
      0 703.657 181.248
      0       0       1

NO PHOTOMETRIC Calibration!
Reading Photometric Calibration from file 
PhotometricUndistorter: Could not open file!
using pyramid levels 0 to 4. coarsest resolution: 77 x 23!
Start Loop Thread
Undistort::undistort: wrong image size (1242 375 instead of 1232 368) 
================================================================================REQUIRED process [direct_stereo_slam-1] has died!
process has died [pid 491, exit code 1, cmd /home/user/catkin_ws/devel/lib/direct_stereo_slam/slam_node __name:=direct_stereo_slam __log:=/root/.ros/log/f9197612-d76c-11ec-be0b-a8a159686689/direct_stereo_slam-1.log].
log file: /root/.ros/log/f9197612-d76c-11ec-be0b-a8a159686689/direct_stereo_slam-1*.log
Initiating shutdown!
================================================================================
[direct_stereo_slam-1] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done  ```

**Comment by YznMur** [comment]
I tried your suggestion but still getting the same error. Here is my logs

**Comment by garriton** [comment]
> I tried your suggestion but still getting the same error. Here is my logs

I use the dataset 'KITTI Visual Odometry sequence 00' , gray images.  Maybe you can try.

**Comment by jiawei-mo** [comment]
> ```
>  * /direct_stereo_slam/T_stereo/cols: 4
>  * /direct_stereo_slam/T_stereo/data: [1, 0, 0, -0.5372...
>  * /direct_stereo_slam/T_stereo/rows: 4
>  * /direct_stereo_slam/bag: /home/user/catkin...
>  * /direct_stereo_slam/calib0: /home/user/catkin...
>  * /direct_stereo_slam/calib1: /home/user/catkin...
>  * /direct_stereo_slam/nogui: True
>  * /direct_stereo_slam/topic0: /kitti/camera_col...
>  * /direct_stereo_slam/topic1: /kitti/camera_col...
>  * /rosdistro: noetic
>  * /rosversion: 1.15.14
> 
> NODES
>   /
>     direct_stereo_slam (direct_stereo_slam/slam_node)
> 
> ROS_MASTER_URI=http://localhost:11311
> 
> process[direct_stereo_slam-1]: started with pid [491]
> 
> =============== PRESET Settings: ===============
> DEFAULT settings:
> - 2000 active points
> - 5-7 active frames
> - 1-6 LM iteration each KF
> - original image resolution
> PHOTOMETRIC MODE WITHOUT CALIBRATION!
> ==============================================
> Reading Calibration from file /home/user/catkin_ws/src/direct_stereo_slam/cams/kitti/0_2/camera0.txt ... found!
> Input resolution: 1241 376
> In: 718.856000 718.856000 607.192800 185.215700 0.000000
> Out: Rectify Crop
> Output resolution: 1232 368
> finding CROP optimal new model!
> initial range: x: -0.8530 - 0.8890; y: -0.2602 - 0.2666!
> iteration 00001: range: x: -0.8488 - 0.8846; y: -0.2602 - 0.2666!
> iteration 00002: range: x: -0.8445 - 0.8801; y: -0.2602 - 0.2666!
> iteration 00003: range: x: -0.8445 - 0.8801; y: -0.2589 - 0.2653!
> iteration 00004: range: x: -0.8445 - 0.8801; y: -0.2576 - 0.2640!
> iteration 00005: range: x: -0.8445 - 0.8801; y: -0.2576 - 0.2640!
> 
> Rectified Kamera Matrix:
> 713.759       0 602.796
>       0 703.657 181.248
>       0       0       1
> 
> NO PHOTOMETRIC Calibration!
> Reading Photometric Calibration from file 
> PhotometricUndistorter: Could not open file!
> Reading Calibration from file /home/user/catkin_ws/src/direct_stereo_slam/cams/kitti/0_2/camera1.txt ... found!
> Input resolution: 1241 376
> In: 718.856000 718.856000 607.192800 185.215700 0.000000
> Out: Rectify Crop
> Output resolution: 1232 368
> finding CROP optimal new model!
> initial range: x: -0.8530 - 0.8890; y: -0.2602 - 0.2666!
> iteration 00001: range: x: -0.8488 - 0.8846; y: -0.2602 - 0.2666!
> iteration 00002: range: x: -0.8445 - 0.8801; y: -0.2602 - 0.2666!
> iteration 00003: range: x: -0.8445 - 0.8801; y: -0.2589 - 0.2653!
> iteration 00004: range: x: -0.8445 - 0.8801; y: -0.2576 - 0.2640!
> iteration 00005: range: x: -0.8445 - 0.8801; y: -0.2576 - 0.2640!
> 
> Rectified Kamera Matrix:
> 713.759       0 602.796
>       0 703.657 181.248
>       0       0       1
> 
> NO PHOTOMETRIC Calibration!
> Reading Photometric Calibration from file 
> PhotometricUndistorter: Could not open file!
> using pyramid levels 0 to 4. coarsest resolution: 77 x 23!
> Start Loop Thread
> Undistort::undistort: wrong image size (1242 375 instead of 1232 368) 
> ================================================================================REQUIRED process [direct_stereo_slam-1] has died!
> process has died [pid 491, exit code 1, cmd /home/user/catkin_ws/devel/lib/direct_stereo_slam/slam_node __name:=direct_stereo_slam __log:=/root/.ros/log/f9197612-d76c-11ec-be0b-a8a159686689/direct_stereo_slam-1.log].
> log file: /root/.ros/log/f9197612-d76c-11ec-be0b-a8a159686689/direct_stereo_slam-1*.log
> Initiating shutdown!
> ================================================================================
> [direct_stereo_slam-1] killing on exit
> shutting down processing monitor...
> ... shutting down processing monitor complete
> done  ```
> ```

It seems like the image size is incorrect. For KITTI, different sequences have different camera intrinsic parameters, please double check that you are using the correct calibration file. For example, the provided `kitti/0_2` is for sequence 00 to sequence 02.

**Comment by jiawei-mo** [comment]
> > I mean the new error : "error: XDG_RUNTIME_DIR not set in the environment." and the "nan" values
> 
> for error: XDG_RUNTIME_DIR change the launch file. add parameter:`<param name="nogui" value="true" />`
> 
> for the "nan" values change the topic0 and topic1 to your rosbag topic
> 
> then i run the direct_stereo_slam, in 3000 + its ,occur the "REQUIRED process [direct_stereo_slam-2] has died! process has died" again , but still haven't solved it, if you occurs it too, pls help

We use `nogui` mode for running test multiple times. I would suggest enable GUI if you suspect if the code finish correctly. 
For "REQUIRED...", removing `required=true` in the launch file might help.

**Comment by garriton** [comment]
> > > I mean the new error : "error: XDG_RUNTIME_DIR not set in the environment." and the "nan" values
> > 
> > 
> > for error: XDG_RUNTIME_DIR change the launch file. add parameter:`<param name="nogui" value="true" />`
> > for the "nan" values change the topic0 and topic1 to your rosbag topic
> > then i run the direct_stereo_slam, in 3000 + its ,occur the "REQUIRED process [direct_stereo_slam-2] has died! process has died" again , but still haven't solved it, if you occurs it too, pls help
> 
> We use `nogui` mode for running test multiple times. I would suggest enable GUI if you suspect if the code finish correctly. For "REQUIRED...", removing `required=true` in the launch file might help.

thank u for your replay， I remove the `nogui` and `required=true`，but still occurs this error 
![image](https://user-images.githubusercontent.com/52850638/169444771-29d8cf6a-83cc-4e06-b986-b55f32382cdf.png)
But the GUI performs really nice. Thank you for opening your code.
