### ISSUE TITLE
Can we retrieve registered point cloud or just the map of landmarks/points

### ISSUE THREAD

**Issue by dt1729** [IRVLab/direct_stereo_slam#4]
Hi although DSO will in theory just provide odometry(Localisation) is it possible to retrieve map of the environment? If stereo DSO cannot do this, shall I look into alternate SLAM algorithms?

**Comment by jiawei-mo** [comment]
Hi,

DSO does export the points: https://github.com/JakobEngel/dso/blob/master/src/IOWrapper/Output3DWrapper.h#L89

Thanks,
Jiawei

**Comment by dt1729** [comment]
Thanks for sharing that in the official thread, i started looking at that later.
