### ISSUE TITLE
The problem of further expansion of the system

### ISSUE THREAD

**Issue by WuZihao12** [IRVLab/direct_stereo_slam#7]
Thank you for your excellent work. Can [direct_stereo_slam](https://github.com/IRVLab/direct_stereo_slam)  be applied to a continuous-time model like [spline_vio](https://github.com/IRVLab/spline_vio) ？

**Comment by jiawei-mo** [comment]
Yes, it is possible. In fact, we have preliminarily implemented it in our [SOS-SLAM](https://github.com/IRVLab/SOS-SLAM).
